### ISSUE TITLE
Outline scope of "Webmaker add-on for Firefox"

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-addons#1]
Clarify the scope, market, etc. of the tool being thought about here: https://github.com/MozillaFoundation/plan/issues/123

**Comment by xmatthewx** [comment]
We will focus on an add-on for desktop, but designed for touch and with an eye on mobile. 

 MVP
- [x] add-on for Firefox desktop
- [x] designed to work on tablet (no mouse, no keyboard)
- user can
  - [ ] start a new creation via context menu on image
  - add images via...
    - [ ] device via file picker
    - [ ] drag from html page
    - [x] via url
    - [ ] ~~small collection of stickers~~ future iteration
  - [x] add text on image with a few style options
  - share as...
    - [ ] image to one social platform
    - [x] new page in thimble or another tool

Does this look right @toolness ?

**Comment by xmatthewx** [comment]
filed as separate issues
