### ISSUE TITLE
Add 'selected' style

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-addons#14]
While an item on the canvas/whiteboard is selected, add appropriate style. Such as...

```
box-shadow:0px 0px 20px rgba(255, 255, 0, 0.5);
cursor:move;
```

**Comment by toolness** [comment]
Dude this would be a great first bug for you! You're welcome to try fixing it yourself--the relevant code should be in `src/selection-frame.jsx`--but if you don't want to or are too busy etc. then no worries :)

**Comment by toolness** [comment]
Oh wait, the `cursor-move` thing might actually not work b/c the `pointer-events` of that thing are null. lemme fix this one myself, I guess.

**Comment by xmatthewx** [comment]
Is it wrong in the react paradigm to assign a class to an element in a certain state? Any reason to not handle this in a global stylesheet?

**Comment by toolness** [comment]
Oh, not at all, I just am so used to CSS growing into an out-of-control mess of stuff that I decided to try just inlining it all since React makes it so easy. It is just an experiment on my part but I have no problem with doing it as a global style thing!
