### ISSUE TITLE
Implement new font picking UI

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-addons#18]
To make things simpler for users, we should select a handful of fonts instead of offering all the fonts.   

We might also fetch the characters in their name so we can show how they look in the menu itself. Like so: http://fonts.googleapis.com/css?family=Opens+Sans&text=OpenSans

A few from the league of moveable type on google fonts: 
Knewave
Londrina Sketch
Pacifico
Open Sans
Prociono

**Comment by toolness** [comment]
Here's the relevant screenshot from [reference.html](http://xmatthewx.github.io/webmaker-addons/reference.html):

![capture](https://cloud.githubusercontent.com/assets/124687/6159427/436a01cc-b223-11e4-945e-f6a3f7f92123.PNG)

**Comment by toolness** [comment]
Done in b65a9af47131259449f81651c199af82425095c5.
