### ISSUE TITLE
Editable Images

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-addons#21]
@toolness had the great idea of baking our json blob into the pngs we generate so that images could be later pulled into Webmaker and edited. Not MVP, but something to keep in mind.

**Comment by davidascher** [comment]
This is totally cool, so cool that I duped it. ;-)

I particularly like the fact that it allows us to have the sharing/social mechanisms not break the opportunity to remix.

**Comment by toolness** [comment]
Hehe, awesome!

This shouldn't be hard to do, I actually busted up [png-baker.js](https://github.com/toolness/png-baker.js#readme) back when I was working on Badges, and it should be pretty quick to embed the data in there before handing it to the user.

The only unfortunate thing is that I've heard many popular websites (I believe FB is one of them) aggressively strip the metadata from these images, which is a bummer. :cry: 

One very weird solution might be to hash the pixel data, which presumably shouldn't change across services, and have a central repository that maps those hashes to remix data. That has funky privacy issues that aren't present in the metadata-embedding approach, though, and would break if even one pixel were altered... ah well.

**Comment by toolness** [comment]
Ok, this has been implemented as of a9318c0e8fa20e17557586a0b5852b631b3d113b, with one really annoying annoyance, which I've documented in #44.
