### ISSUE TITLE
SVG files in img and css background URLs don't inherit from parent stylesheets

### ISSUE THREAD

**Issue by toolness** [mozilla/webmaker-addons#27]
What this means for us is that when there's `<text font-family="FontAwesome">` in an SVG, the embedding HTML page isn't consulted for that font, so any glyphs using the font don't show up as intended unless the user has the font installed globally on their filesystem.

For instance, this is what [src/icons/TrashIcon.svg](https://github.com/xmatthewx/webmaker-addons/blob/gh-pages/src/icons/TrashIcon.svg) looks like when embedded in [reference.html](https://github.com/xmatthewx/webmaker-addons/blob/gh-pages/reference.html) on my system, which doesn't have Font Awesome installed at the OS level:

![capture](https://cloud.githubusercontent.com/assets/124687/6149008/af64d532-b1d3-11e4-92a4-0e0c87363e2a.PNG)

One possibility might be to figure out how to link to a CSS stylesheet in the SVG file itself, if that's even possible, but I'm not a huge fan of that because it makes the SVG non-portable if the URL isn't absolute. It would probably be easiest to just tell Sketch/Illustrator to vectorize text when exporting, though it will result in larger SVG files.

**Comment by xmatthewx** [comment]
Ack. My mistake. We should definitely vectorize. Maybe Ricardo or Jess can lend a hand for Friday.

**Comment by xmatthewx** [comment]
This is covered by #29, correct?
