### ISSUE TITLE
Let's not use the word webmaker in the sidebar

### ISSUE THREAD

**Issue by davidascher** [mozilla/webmaker-addons#30]
Trying to avoid a big branding discussion here, so maybe we just remove the header for now?

**Comment by toolness** [comment]
I'd like to remove the header, but it seems to be something that the Add-on SDK's [sidebar](https://developer.mozilla.org/en-US/Add-ons/SDK/Low-Level_APIs/ui_sidebar) functionality is including... If I can't figure out how to remove the header entirely by demo time, any suggestions on a replacement name?

Oh, also, the sidebar name shows up under **View -> Sidebar** in the menu bar, so I think it will need some kind of replacement name regardless?

**Comment by toolness** [comment]
Also, should I rename the addon itself from "webmaker-addon" to something else? It shows up in `about:addons` like this right now:

![capture](https://cloud.githubusercontent.com/assets/124687/6160607/22f8e164-b233-11e4-94cb-91ba306a1cdc.PNG)

**Comment by xmatthewx** [comment]
A few placeholder ideas:

Image Capture
Image Sidebar
Image Maker

**Comment by davidascher** [comment]
Image Maker wfm.
