### ISSUE TITLE
Implement resize handle on images

### ISSUE THREAD

**Issue by davidascher** [mozilla/webmaker-addons#31]
If I make the sidebar narrow and import a large image, it is squeezed to fit in the sidebar, and the slider won't let me grow past 100%.  

The easiest thing is maybe to let people resize the image by grabbing a corner, as opposed to using a slider?

**Comment by toolness** [comment]
Yep! That is actually what I'm gonna be working on tomorrow! Sorry a bug hasn't yet been filed for it... but I guess you just did that for us. :smile:
