### ISSUE TITLE
Put the + button snug in the top-left

### ISSUE THREAD

**Issue by davidascher** [mozilla/webmaker-addons#32]
I keep hitting the + button instead of the archive button in gmail =)

![screenshot 2015-02-11 13 54 10](https://cloud.githubusercontent.com/assets/51278/6158053/833607c4-b1fb-11e4-95c7-b9a05462e6fa.png)

**Comment by toolness** [comment]
Hah! Ok, will fix this tomorrow.

**Comment by toolness** [comment]
I'm hoping that my fix for #33 fixes this too, but feel free to reopen if you think it doesn't.

(BTW, Mattheww's original mockups had the **+** icon shown at top-right, so that's what my changes do as well.)
