### ISSUE TITLE
Consider only showing the + on images larger than a certain size

### ISSUE THREAD

**Issue by davidascher** [mozilla/webmaker-addons#33]
It feels to me like small icons aren't likely useful, and the +'s definitely get in the way of generally using the web.

**Comment by toolness** [comment]
Ok, I've changed things in dc2e7f82aae2a0848fe9d2c4c35a4b7341061636 so they work as follows:
- If the target image is less than 24 pixels in either dimension, no **+** icon is shown.
- If the target image is between 25 and 47 pixels in either dimension, a tiny 12x12 **+** icon is shown, e.g. on nytimes.com:
  
  ![capture2](https://cloud.githubusercontent.com/assets/124687/6161138/86629644-b23a-11e4-99ca-644c103c46a3.PNG)
- If the target image is greater than or equal to 48 pixels in either dimension, a 16x16 **+** icon is shown, e.g. on nytimes.com:
  
  ![capture1](https://cloud.githubusercontent.com/assets/124687/6161137/84a51106-b23a-11e4-913f-85a80716279b.PNG)

We can play with the threshholds and scaling amounts but this seems like a decent solution for now, so I'm closing but feel free to re-open if you think it's suboptimal.

**Comment by davidascher** [comment]
Cool sounds good will play with it.
