### ISSUE TITLE
Revamp sharing modal

### ISSUE THREAD

**Issue by toolness** [mozilla/webmaker-addons#40]
This is what it looks like in [reference.html](http://xmatthewx.github.io/webmaker-addons/reference.html):

![screen shot 2015-02-12 at 1 31 37 pm](https://cloud.githubusercontent.com/assets/124687/6174271/a9607b8a-b2bb-11e4-8c0c-70d921548149.png)

I guess doing a lot of the social network options will mean hosting the image somewhere first.

**Comment by davidascher** [comment]
For the purpose of demo, we can just make an unauthed POST-to-s3 endpoint.

**Comment by xmatthewx** [comment]
Would be nice to auto copy url to clipboard and notify user.

**Comment by xmatthewx** [comment]
The webmaker icon could pop open your modal with him.

**Comment by xmatthewx** [comment]
Ha. Auto correct. Html, not him.

**Comment by xmatthewx** [comment]
For demo, share could include 3 buttons. Text labels are fine. View Image, Copy Link, Share as a Page.

**Comment by toolness** [comment]
Ok, I've got this done for the demo... don't have it uploading to S3 or anything but can add that later, which I filed #43 for.
