### ISSUE TITLE
Implement social network sharing

### ISSUE THREAD

**Issue by toolness** [mozilla/webmaker-addons#43]
Currently clicking on the Facebook icon when sharing just raises a modal telling the user that the feature is unimplemented. We should actually upload the image somewhere and then use various social network sharing APIs to blah

**Comment by xmatthewx** [comment]
Facebook, imgur, reddit seem like good destinations.

**Comment by xmatthewx** [comment]
choose 1 or 2
- facebook
- reddit
- imgur
- ~~instagram~~
- tumblr
- snapchat

**Comment by toolness** [comment]
Alas, looks like [snapchat has no official API](http://blog.snapchat.com/post/99998266095/third-party-applications-and-the-snapchat-api).

**Comment by toolness** [comment]
Curious if we want to integrate with [Filepicker.io](https://filepicker.io/), or if that would overwhelm the user with choices?

**Comment by davidascher** [comment]
If filepicker.io is a shortcut-to-a-good-demo, go ahead.

**Comment by xmatthewx** [comment]
Isn't filepicker.io for uploads and exporting to the filesystem? Or will it help us move web content to a social service?

**Comment by toolness** [comment]
It's for both... here's what it looks like, as of 559edfa95c33aa848bab3e23af9e593db44e79c8:

![upload](https://cloud.githubusercontent.com/assets/124687/6252644/c7855dee-b769-11e4-8627-7e70a97c27b5.gif)

**Comment by xmatthewx** [comment]
Cool. That's great. Should we load that in the sidebar itself? This is fine for now. (note: I had to delete and reinstall [the addon](xmatthewx.github.io/webmaker-addons/addon/webmaker-addon.xpi).)

We can remove the download button since this handles that.
