### ISSUE TITLE
Transfer this repository to mozilla org

### ISSUE THREAD

**Issue by simonwex** [mozilla/webmaker-addons#54]
Hey @xmatthewx could you transfer this repo to the mozilla org so more people have access to it?

**Comment by xmatthewx** [comment]
Sure. The addon is served via gh-pages. @toolness -- let's coordinate. Github apparently doesn't fwd links to pages like it does for repos.

**Comment by xmatthewx** [comment]
Repo has been moved. I updated urls (https://github.com/mozilla/webmaker-addons/commit/5f0aecb0ee1e9aa56a6bbd9474aae3687fed9937). I will let @toolness re-package the addon so I don't muck anything up.
