### ISSUE TITLE
Slide-ify this prototype

### ISSUE THREAD

**Issue by simonwex** [mozilla/webmaker-addons#55]
We need a video, animation or other method for showing this concept off in Monday's presentation.

**Comment by toolness** [comment]
Here's a first attempt at it, one minute long:

https://toolness-fun.s3.amazonaws.com/one-minute-image-maker-demo.mp4

I don't delve into any of the more "advanced" features like being able to drag an exported image back into a sidebar to remix it or anything, though.

**Comment by xmatthewx** [comment]
That's great. If you feel inclined to do a second take, I would deselect the text before sharing.
