### ISSUE TITLE
Importing an image doesn't always put it at the top of the composition

### ISSUE THREAD

**Issue by toolness** [mozilla/webmaker-addons#60]
This often happens when there are already other images in the composition but the sidebar wasn't showing before the image was added; firebase hasn't yet synced with the iframe, and the new image is pushed onto the composition as the sole image. Moments later, firebase is synced and the pre-existing images appear atop the one that was just added.

At least, that's what I _think_ is going on.

**Comment by xmatthewx** [comment]
Interesting. Good catch. Can we assign a z-index of 100 to any new item added, but iterate from 10 for things coming via firebase?
